### ISSUE TITLE
ELECTRON INTEGRATION - AUTHENTICATION ISSUE

### ISSUE THREAD

**Issue by andresdev16** [patrickjquinn/P-Brain.ai#76] opened 2020-01-30 10:30 UTC
Hello, I am integrating and because to log in it is necessary to do it from a pop-up window, in electron it is not possible to do it. I would like to know what is the fraction of code that is responsible for displaying this pop-up window and how I could do to login with HTML.

I'm getting the message "unauthorized".

**Comment by patrickjquinn** [comment] 2020-01-30 10:32
Electron isnt supported as it doesn’t allow for the good speech API,

Does it work for you in the browser?

**Comment by andresdev16** [comment] 2020-01-30 10:36
What alternative for electron? . In the browser it is perfect, anyway I would like to change from a popup window to HTML.

**Comment by timstableford** [comment] 2020-02-16 23:14
It uses HTTP basic auth. Closing as a duplicate of #77 where I've gone into some detail.

**Closed by timstableford** 2020-02-16 23:14 UTC
