### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:4567

### ISSUE THREAD

**Issue by GlennSchnieders** [patrickjquinn/P-Brain.ai#18] opened 2017-01-31 22:35 UTC
After following steps (of installing yarn), I still get follow error when I run yarn start `Error: connect ECONNREFUSED 127.0.0.1:4567`. Do I need to specify the API keys before I can use a simple command (like hello Brian)?

**Comment by patrickjquinn** [comment] 2017-02-01 08:14
Can you give me more details about the environment you are running this on? Are you running this on the same machine / subnet that you're accessing the client from?

**Comment by GlennSchnieders** [comment] 2017-02-01 08:22
I'm trying to run it on a Raspberry pi (3) (via ssh).

Op wo 1 feb. 2017 om 09:14 schreef Pat Quinn <notifications@github.com>

**Comment by patrickjquinn** [comment] 2017-02-01 08:28
Ah you'll need 2 things `sudo`when running the automatic installer and then to add  `sudo DISPLAY=:0 npm start` to the run.sh in place of `npm start` at the bottom.

**Comment by patrickjquinn** [comment] 2017-02-01 08:28
I'd suggest deleting the repo you've cloned and just running 

`sudo curl -sL https://raw.githubusercontent.com/patrickjquinn/P-Brain.ai-RasPi/master/raspberrypi.sh | bash`

**Comment by GlennSchnieders** [comment] 2017-02-01 08:40
Ok, will try that later. After deleting/reinstalling the repo, do I have to
do anything else? Reinstall yarn?

Op wo 1 feb. 2017 om 09:28 schreef Pat Quinn <notifications@github.com>

**Comment by patrickjquinn** [comment] 2017-02-01 08:41
Yarn isn't available on the RasPi properly so the automation script does everything via NPM :)

**Comment by GlennSchnieders** [comment] 2017-02-01 18:02
Now It works, now trying to let it work with my build-in microphone on my macbook.

**Comment by GlennSchnieders** [comment] 2017-02-01 18:22
Also I can not 'talk' to the one you put on the project site (https://13.67.178.211:4567/). Is that a setting on my computer (I checked al the settings)?

**Comment by patrickjquinn** [comment] 2017-02-01 18:38
Make sure it's not running elsewhere (I.e in another tab) and make sure you've clicked through the "proceed to page" dialog on tha page. Once again make sure you're using the latest chrome. Actually would you mind sending me a screenshot of the live demo as you see it?

**Comment by GlennSchnieders** [comment] 2017-02-01 19:06
> Make sure it's not running elsewhere (I.e in another tab) and make sure you've clicked through the "proceed to page" dialog on tha page. Once again make sure you're using the latest chrome. Actually would you mind sending me a screenshot of the live demo as you see it?

After I updated my Chrome to the latest version, it worked for a couple of minutes. Now the microphone icon is just blinking... Didn't changed anything after the first successful attempt.

**Comment by patrickjquinn** [comment] 2017-02-01 19:26
Blink would insinuate a network error with speech recognition, are you using Chrome or Chromium?

**Comment by GlennSchnieders** [comment] 2017-02-01 19:42
> Blink would insinuate a network error with speech recognition, are you using Chrome or Chromium?

I'm using Chrome (latest version), is it possible that I'm missing also some help text (next to the microphone icon? 

<img width="666" alt="schermafbeelding 2017-02-01 om 20 41 31" src="https://cloud.githubusercontent.com/assets/1309276/22523258/ff6c4bfe-e8be-11e6-97d0-dfe49ce17431.png">

**Comment by patrickjquinn** [comment] 2017-02-01 20:00
Ah. Okay 'just a second' going on forever would suggest that the API is down. Can you verify that this is the live demo on patrickjquinn.github.io/P-Brain.ai/ and not your local machine and that you're not seeing any errors in the browser's console?

**Comment by patrickjquinn** [comment] 2017-02-03 19:48
Closing this for now as i've been unable to reproduce, let me know about the above and I can re-open and further investigate 👍

**Closed** 2017-02-03 19:47 UTC
