### ISSUE TITLE
Update node js

### ISSUE THREAD

**Issue by lavrenkov-sketch** [patrickjquinn/P-Brain.ai#71] opened 2019-07-19 23:03 UTC
how to run the project on the latest version of node js, what needs to be rewritten or is it impossible ????

**Comment by patrickjquinn** [comment] 2019-07-19 23:49
Can you explain to me what the error is when trying to running it under njs 12 +? I can only help you if you help me 😉

**Comment by lavrenkov-sketch** [comment] 2019-07-20 07:41
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/12.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/webworker-threads/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/webworker-threads/.node-gyp'
gyp ERR! System Linux 5.1.16-050116-generic
gyp ERR! command "/usr/local/lib/nodejs/node-v12.6.0-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v12.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/webworker-threads
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> libxmljs@0.18.8 install /home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp ERR! Pre-built binaries not installable for libxmljs@0.18.8 and node@12.6.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/build' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/12.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/.node-gyp'
gyp ERR! System Linux 5.1.16-050116-generic
gyp ERR! command "/usr/local/lib/nodejs/node-v12.6.0-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v12.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/build/Release" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/lib/nodejs/node-v12.6.0-linux-x64/bin/node /usr/local/lib/nodejs/node-v12.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/build/Release --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.1.16-050116-generic
node-pre-gyp ERR! command "/usr/local/lib/nodejs/node-v12.6.0-linux-x64/bin/node" "/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs
node-pre-gyp ERR! node -v v12.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/lib/nodejs/node-v12.6.0-linux-x64/bin/node /usr/local/lib/nodejs/node-v12.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/lavrenkov/Desktop/хлам new/vika_stable/node_modules/libxmljs/build/Release --napi_version=4 --node_abi_napi=napi' (1)
npm WARN P-Brain.ai@0.5.3 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.17 (node_modules/webworker-threads):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: webworker-threads@0.7.17 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.18.8 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-20T07_38_13_411Z-debug.log

**Comment by timstableford** [comment] 2020-01-07 20:10
This was caused by the Wolfram package being unmaintained. The build should work now. @lavrenkov-sketch would you please confirm?

**Comment by timstableford** [comment] 2020-02-16 23:15
Closing because assumed resolved

**Closed by timstableford** 2020-02-16 23:15 UTC
